### ISSUE TITLE
Scenario for clients to limit trust of a signing key

### ISSUE THREAD

**Issue by sudo-bmitch** [notaryproject/notaryproject#42]
As a variation on [requirement 6](https://github.com/notaryproject/requirements/blob/main/scenarios.md#scenario-6-multiple-signatures), I believe it would be useful to have a scenario to allow clients to limit the scope of trust for a key to a specific registry, repository, path on a registry (containing multiple repositories), or a list of any of the above. This would allow a client to be configured to trust images pulled from ACME rockets only when signed with a signature for that organization, not to trust any other signatures for that path, and not to trust images signed with the ACME rockets key when they are found in other repositories.

In a more practical sense, this limits the blast radius of a compromised key. A malicious actor may not have push access to the repository, or they may want to avoid pushing malicious images to a well known and monitored repository. If they can use that key to push malicious images to a new repository, possibly on another registry server, then clients configured to only run signed images should reject that other repository as untrusted for that key.

**Comment by SteveLasker** [comment]
These are great rules to incorporate in the policy implementations of notary.

**Comment by yizha1** [comment]
Closed by support of [Trust Policy ](https://github.com/notaryproject/notaryproject/blob/v1.0.0-draft.3/trust-store-trust-policy-specification.md)
