### ISSUE TITLE
Singularity related background

### ISSUE THREAD

**Issue by dtrudg** [notaryproject/notaryproject#5]
Hi all - I was asked to write a bit from the Singularity point of view r.e. Notary v2 and ORAS. I figured it'd be good to just get something down quickly on an issue here, and let others from Sylabs and elsewhere comment, rather than delaying. Also, I don't want to clog up the main scenarios documents etc. with background that isn't very relevant.

## Singularity Signing - Background

Singularity's main container format is a single `.sif` file. The SIF file can have multiple descriptors -  with one of those pointing to a container rootfs, which is a squashfs.

We can `singularity sign` an image that we are happy with using a PGP keypair (I have a single one setup here, so no prompts/specification of which key)...

```
dave@piran~> singularity sign ubuntu_latest.sif
Signing image: ubuntu_latest.sif
Enter key passphrase :
Signature created and applied to ubuntu_latest.sif
```

Singularity is computing the signature over the rootfs part of the SIF by default. Metadata is, for historical reasons (singularity used to use bare squashfs images), inside the rootfs. This is changing as we transition metadata into SIF descriptors fully.

The signature is appended as a new descriptor in the SIF file...

```
dave@piran~> singularity sif list ubuntu_latest.sif
Container id: 9e2acf8a-fbd2-4786-a29d-a6cf0a513137
Created on:   2020-02-06 16:59:38 -0600 CST
Modified on:  2020-02-12 12:36:15 -0600 CST
----------------------------------------------------
Descriptor list:
ID   |GROUP   |LINK    |SIF POSITION (start-end)  |TYPE
------------------------------------------------------------------------------
1    |1       |NONE    |32768-32800               |Def.FILE
2    |1       |NONE    |36864-36961               |JSON.Generic
3    |1       |NONE    |40960-25899008            |FS (Squashfs/*System/amd64)
4    |1       |3       |25899008-25899963         |Signature (SHA384)
```

The SIF container image can be `singularity verify`-ed using the public key added into the local keyring used by Singularity, or with retrieval from a keyserver as part of our Cloud/Enterprise product....

```
dave@piran~> singularity verify ubuntu_latest.sif
Container is signed by 1 key(s):

Verifying partition: FS:
2CD26E9A44F98770792C8CE1CE7D6E2D9722F32D
[LOCAL]   David Trudgian (Test) <dave@trudgian.net>
[OK]      Data integrity verified

INFO:    Container verified: ubuntu_latest.sif
```

You can `singularity sign` an image multiple times, with multiple keys, e.g. as an image goes through a QA pipeline. The singularity runtime can be configured to require a valid signature associated with any of N keys, all of N keys, etc.

If I dump the signature portion of the file you'll see that there's a computed hash over the portion(s) of the SIF that were signed, and a PGP signature over that.

```
dave@piran~> singularity sif dump 4 ubuntu_latest.sif
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

SIFHASH:
17548c8f52c6f77d22c0c1880670d009a3634ba6e7338b75ad16385427e369b56afe712c8eecbece3c09c2dfb609f61f
-----BEGIN PGP SIGNATURE-----

wsFcBAEBCAAQBQJeREWfCRDOfW4tlyLzLQAAPjYQAIPc9Fbeit/7cZe/vHiRVAh7
4kyfzJkGyaeZle1uBaDI7xGU7pDI4fft8RJid7nA5tp9Zvt63xyGLxdRmiT8gK1R
ik1V3RqAQ5ldGhc7NQqmIv7NdwvNcmSTSCaVbypm/u3ep+TTB6QaBt2axD6B9ieF
I7QW6LXaXGxHKYK2GPOibjfEE4cxlPrsStwTKev+rnUGwvXuADZfyMXqm+sbHkeb
HEzOMmcnTSk4ePTz9jlKS3ntzO44/E4UHtegSIvLGhH2nJ4GrCeS2I1RNWL6IwoV
SmkrJ8csedahvf1P840lrCK+laTS0Ei7HMi79/R6NCDZWbLMNbAQDKcLpDfZUJAT
+5nJrM3Uac/JoUkWVn6ZfTj+y4wScKdKe4Szn7+o+N0fnAOJqLerPpRL0v9V/p6V
vi13XGIWdCzTXCsqYj62iaU3is22C/NUFBap/KBQqCUx0/rozmBpNpip7iomBolD
45vQN6W+46QrccT75iUDifm2y7qlzhCvI5q+rUyHp/N7V2Cb3Vdch82YO9JtwGq0
Vu/owh5vYqlbNPB2cjewx6FA1y48c7jnCH/fuLdtXvWWnGGlPW24lUpfPNBCJPAv
fmkSZ7P1Vv4PK+MBdsts8lJzP2Opuc8NunRbRuabaph50FH5RSzRRVHqmTM/ReTB
cYske6gSlnzHh23AVV6H
=BhX1
-----END PGP SIGNATURE-----
```

## Singularity Interest in Notary v2

There are 2 areas of interest for us with Notary v2:

### 1. Handling Notary v2 OCI/docker images

Much use of Singularity is to run OCI/docker images on systems where Singularity is the preferred container runtime. When Notary v2 gets out into the wild and is adopted, we need to be able to deal with pulling/converting/running signed stuff in a nice manner.

We are using `containers/image`, `openSUSE/umoci` etc. to handle our `docker://` and other docker/OCI related source URIs - so it's likely we benefit from other's implementations of verification. We do need to understand how things are going to work, though, to make sure we fit it all in nicely to the singularity CLI and workflow that people are familiar with.

### 2. Singularity Images Distributed via ORAS

We have functionality for distributing Singularity `.sif` file images via registries that support ORAS.

We need to understand how signing will be implemented for arbitrary artifacts. We'd like to develop thoughts around how a Notary v2 ORAS signing model can be implemented in the Singularity CLI such that it doesn't feel like a completely separate 'add-on' to the native signing/verification of our SIF images. 

We need to think about what the relationship is between a signature embedded in a SIF image, and a Notary v2 signature associated with an SIF image artifact. A signature over the artifact 'wraps' the entire content of the SIF file, including its embedded signatures.

## Scenarios

We'll try to have a think about some specific scenarios that involve Singularity - but generally it's the same kind of stuff as in the existing scenarios PR, but with Singularity as software used to build/execute/both a container. We might be building/pushing/running SIFs, or we might be pulling and running signed OCI/docker stuff.

**Comment by SteveLasker** [comment]
Moving to a discussion to capture the info, with closure on inactive issues.
